# build env
FROM node:16-alpine as build

WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
COPY . ./
RUN yarn run build

# production env
FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]