import { createStore } from "vuex";

export default createStore({
  state: {
    node: [
      {
        name: "Akash",
        status: "active",
        link: "https://ping.pub/akash-network/staking/akashvaloper1uepjmgfuk6rnd0djsglu88w7d0t49lmlsqkfuf",
        address: "akashvaloper1uepjmgfuk6rnd0djsglu88w7d0t49lmlsqkfuf",
        coingecko_id: "akash-network",
        rpc: "https://rpc.akash.forbole.com:443",
        decimals: 6,
      },
      {
        name: "Chihuahua",
        status: "active",
        link: "https://ping.pub/chihuahua/staking/chihuahuavaloper1zl4vt84hya03e8hu7dx4q4cvn2ts2xdr685p5g",
        address: "chihuahuavaloper1zl4vt84hya03e8hu7dx4q4cvn2ts2xdr685p5g",
        coingecko_id: "chihuahua-token",
        rpc: "https://rpc.chihuahua.wtf/",
        decimals: 6,
      },
      {
        name: "Evmos",
        status: "active",
        link: "https://www.mintscan.io/evmos/validators/evmosvaloper1pz3mcahcrglf3md4lggax5r95gvmppc6x5w7hw",
        address: "evmosvaloper1pz3mcahcrglf3md4lggax5r95gvmppc6x5w7hw",
        coingecko_id: "evmos",
        rpc: "https://tendermint.bd.evmos.org:26657",
        decimals: 18,
      },
      {
        name: "Nomic",
        status: "active",
        link: "https://nomic.zenscan.io/validator.php?addr=nomic1jndxttq5ykp5zc8g3xwnxmchzjtl7ap2avlwkz",
        address: "nomic1jndxttq5ykp5zc8g3xwnxmchzjtl7ap2avlwkz",
        coingecko_id: "nomic",
        rpc: "http://138.197.71.46:26657",
        decimals: 6,
      },
      {
        name: "Sentinel",
        status: "active",
        link: "https://www.mintscan.io/sentinel/validators/sentvaloper1wcyvemaw8m4fxwnsljghe5wtd9t6q0smaq64ef",
        address: "sentvaloper1wcyvemaw8m4fxwnsljghe5wtd9t6q0smaq64ef",
        coingecko_id: "https://rpc.cosmos.directory/sentinel",
        rpc: "",
        decimals: 6,
      },
      {
        name: "Juno",
        status: "active",
        link: "https://www.mintscan.io/juno/validators/junovaloper1uepjmgfuk6rnd0djsglu88w7d0t49lml7kqufu",
        address: "junovaloper1uepjmgfuk6rnd0djsglu88w7d0t49lml7kqufu",
        coingecko_id: "juno-network",
        rpc: "https://rpc.cosmos.directory/juno",
        decimals: 6,
      },
      {
        name: "Passage",
        status: "active",
        link: "https://www.mintscan.io/passage/validators/pasgvaloper1uepjmgfuk6rnd0djsglu88w7d0t49lml8ax6e6",
        address: "pasgvaloper1uepjmgfuk6rnd0djsglu88w7d0t49lml8ax6e6",
        coingecko_id: "",
        rpc: "https://rpc.cosmos.directory/passage",
        decimals: 6,
      },
      {
        name: "Cosmos Hub",
        status: "unbounded",
        link: "https://www.mintscan.io/cosmos/validators/cosmosvaloper1uepjmgfuk6rnd0djsglu88w7d0t49lmljdpae2",
        address: "cosmosvaloper1uepjmgfuk6rnd0djsglu88w7d0t49lmljdpae2",
        coingecko_id: "cosmos",
        rpc: "https://rpc.cosmos.directory/cosmoshub",
        decimals: 6,
      },
    ],
  },
  getters: {},
  mutations: {},
  actions: {},
  modules: {},
});
